In [1]:
from utils import readable_card_to_int
import numpy as np
from config import Config
from view import player_view, human_readable_view
from transition import step_state, init_state
from cardlib import hand_rank,encode
from datatypes import Player

In [2]:


# global_state = np.zeros(config.global_state_shape)
# # set stacks for two players
# board_cards = [('A', 's'), ('K', 's'), ('Q', 's'), ('J', 's'), ('T', 's')]
# board = [readable_card_to_int(card) for card in board_cards]
# hand1 = [('A', 'h'), ('K', 'h'), ('Q', 'h'), ('J', 'h')]
# hand1 = [readable_card_to_int(card) for card in hand1]
# hand2 = [('A', 'c'), ('K', 'c'), ('9', 's'), ('8', 's')]
# hand2 = [readable_card_to_int(card) for card in hand2]
# # flatten hand1 and hand2
# hand1 = [item for sublist in hand1 for item in sublist]
# hand2 = [item for sublist in hand2 for item in sublist]
# board = [item for sublist in board for item in sublist]
# hands = [hand1,hand2]
# print(board)
# print('hands', hands)
# print(global_state.shape)
# for i in range(1, 3):
#     global_state[config.global_state_mapping[f'player_{i}_stack']] = 100
#     global_state[config.global_state_mapping[f'player_{i}_active']] = 1
#     global_state[config.global_state_mapping[f'player_{i}_position']] = i
#     global_state[config.global_state_mapping[f'player_{i}_hand_range'][0]:config.global_state_mapping[f'player_{i}_hand_range'][1]] = hands[i-1]

# board = [13, 4, 12, 4, 11, 4, 10, 4, 9, 4]
# hands = [[13, 3, 12, 3, 11, 3, 10, 3], [13, 1, 12, 1, 8, 4, 7, 4]]

# print(encode([13,3]))
# en_hand = [encode(hands[1][i*2:(i*2)+2]) for i in range(0,len(hands[1])//2)]
# en_board = [encode(board[i*2:(i*2)+2]) for i in range(0,len(board)//2)]
# print(hand_rank(en_hand,en_board))
# hand_values = []
# for i in range(1,7):
#     if global_state[config.global_state_mapping[f'player_{i}_active']] == 1:
#         hand_start = config.global_state_mapping[f'player_{i}_hand_range'][0]
#         hand_end = config.global_state_mapping[f'player_{i}_hand_range'][1]
#         player_hand = [int(h) for h in global_state[hand_start:hand_end]]
#         print('player_hand', player_hand)
#         encoded_hand = [encode(player_hand[i*2:(i*2)+2]) for i in range(0,len(player_hand)//2)]
#         hand_value = hand_rank(encoded_hand, en_board)
#         hand_values.append(Player(global_state[config.global_state_mapping[f'player_{i}_position']],
#                                     global_state[config.global_state_mapping[f'player_{i}_stack']],
#                                     global_state[config.global_state_mapping[f'player_{i}_active']],
#                                     hand_value))
# # find winners

# Testing the environment

In [3]:
config = Config(num_players=2)
CALL = 2
CHECK = 1
player_index = 1
state,done,winnings,action_mask = init_state(config)
print(action_mask)
state,done,winnings,action_mask = step_state(state,CALL,config)
print(action_mask)
while not done:
    print('street',state[-1,config.global_state_mapping['street']])
    print(state.shape)
    state,done,winnings,action_mask = step_state(state,CHECK,config)
    print(done)
    print(action_mask)
print(winnings)
# player_state = human_readable_view(state,player_index,config)
# print(player_state)

[1 0 1 1 1 1 1 1 1 1 1]
1.0
1.0
[1 0 1 1 1 1 1 1 1 1 1]
1.0
(3, 91)
1.0
1.0
1.0
True
[1 0 1 1 1 1 1 1 1 1 1]
{6.0: 0.0}
